services:
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: tenant_db
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  data-ingestion-service:
    build: .
    container_name: data_ingestion_service
    ports:
      - "80:8002"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres.yejyjlowfczcdbsrtuom:zgGSh86li5PHp4pV@aws-1-ap-south-1.pooler.supabase.com:5432/postgres
      TENANT_SERVICE_URL: http://tenant_service:8008
      LOG_LEVEL: INFO
    networks:
      - replystem-network
    # depends_on:
    #   postgres:
    #     condition: service_healthy

networks:
  replystem-network:
    external: true

# volumes:
#   postgres_data:
