"""create ingested_messages table

Revision ID: 037e45755277
Revises: 
Create Date: 2026-01-26 18:40:01.743813
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '037e45755277'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_messages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion'
    )
    op.create_index('idx_messages_created', 'ingested_messages', ['created_at'], unique=False, schema='ingestion')
    op.create_index('idx_messages_platform', 'ingested_messages', ['platform'], unique=False, schema='ingestion')
    op.create_index('idx_messages_tenant', 'ingested_messages', ['tenant_id'], unique=False, schema='ingestion')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('idx_messages_tenant', table_name='ingested_messages', schema='ingestion')
    op.drop_index('idx_messages_platform', table_name='ingested_messages', schema='ingestion')
    op.drop_index('idx_messages_created', table_name='ingested_messages', schema='ingestion')
    op.drop_table('ingested_messages', schema='ingestion')
    # ### end Alembic commands ###
